
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label labelNumero;
	private global::Gtk.Button buttonJugar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelNumero = new global::Gtk.Label ();
		this.labelNumero.Name = "labelNumero";
		this.vbox1.Add (this.labelNumero);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelNumero]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.buttonJugar = new global::Gtk.Button ();
		this.buttonJugar.CanFocus = true;
		this.buttonJugar.Name = "buttonJugar";
		this.buttonJugar.UseUnderline = true;
		this.buttonJugar.Label = global::Mono.Unix.Catalog.GetString ("Jugar");
		this.vbox1.Add (this.buttonJugar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonJugar]));
		w2.Position = 2;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 627;
		this.DefaultHeight = 555;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
